#!/usr/bin/env python3
"""Build ar.html — the Arabic (RTL) edition of the portfolio — from index.html.

Single source of truth: index.html + tools/ar_strings.json (en -> ar).
Run after ANY index.html edit:   python3 tools/build_ar.py
Reports every translation key that no longer matches index.html.
"""
import html, json, pathlib, re, sys

R = pathlib.Path(__file__).resolve().parents[1]
src = (R / "index.html").read_text(encoding="utf-8")
MAP = json.loads((R / "tools" / "ar_strings.json").read_text(encoding="utf-8"))
MAP = [{"en": e[0], "ar": e[1], "all": bool(e[2]) if len(e) > 2 else False} if isinstance(e, list) else e
       for e in MAP]
norm = lambda s: re.sub(r"\s+", " ", s.replace("\xa0", " ")).strip()


def sub1(pat, rep, what):
    global src
    out, n = re.subn(pat, rep, src, flags=re.S, count=1)
    assert n == 1, f"NOT FOUND: {what}"
    src = out


# --- 1. structure: the edition replaces the inline Arabic section -------------------
assert "ar-section" not in src, "index.html still carries the inline Arabic section"
sub1(r'<a class="lang-tab" href="ar\.html"[^>]*>[^<]*</a>',
     '<a class="lang-tab" href="index.html" hreflang="en" lang="en">English</a>', "language tab")
sub1(r'<html lang="en">', '<html lang="ar" dir="rtl">', "html element")
src = (src.replace('<meta property="og:locale" content="en_US">', '<meta property="og:locale" content="ar_SA">')
          .replace('<meta property="og:url" content="https://amz34.github.io/voice-portfolio/">',
                   '<meta property="og:url" content="https://amz34.github.io/voice-portfolio/ar.html">'))

# --- 2. translations: markup-exact pass, then visible-text pass ---------------------
missed = []
for e in MAP:
    parts = [re.escape(p) for p in re.split(r"\s+", e["en"].strip())]
    rx = re.compile(r"(?:\s|&nbsp;|&#160;)+".join(parts).replace("&", "&(?:amp;)?"), re.S)
    src, n = rx.subn(lambda m: e["ar"], src, count=0 if e.get("all") else 1)
    if not n:
        missed.append(e["en"])

bykey = {norm(e["en"]): e["ar"] for e in MAP}
src = re.sub(r">([^<>]{2,400})<",
             lambda m: ">" + (bykey.get(norm(html.unescape(m.group(1)))) or m.group(1)) + "<", src)

# attribute copy (placeholder / title / aria-label / alt) — exact value match
src = re.sub(r'="([^"<>]{3,200})"',
             lambda m: '="' + (bykey.get(norm(html.unescape(m.group(1)))) or m.group(1)) + '"', src)

# --- 3. this edition opens with the Arabic voice CV --------------------------------
src = src.replace('<audio id="vcAudio" preload="metadata" src="assets/voice-cv.mp3">',
                  '<audio id="vcAudio" preload="metadata" src="assets/voice-cv-ar.mp3">')
sub1(r'<button data-cv-lang="en" class="on">', '<button data-cv-lang="en">', "vc lang en")
sub1(r'<button data-cv-lang="ar">', '<button data-cv-lang="ar" class="on">', "vc lang ar")
src = src.replace('aria-label="Voice CV language"', 'aria-label="لغة السيرة الصوتية"')

kb = json.loads((R / "assets/voice/kb.js").read_text(encoding="utf-8").split("=", 1)[1].strip().rstrip(";"))
sub1(r'(<p id="vcText"[^>]*>)(.*?)(</p>)',
     lambda m: m.group(1).replace('dir="ltr"', 'dir="rtl"').replace('lang="en"', 'lang="ar"')
               + html.escape(kb["cv"]["ar"]) + m.group(3), "vcText transcript")

# --- 4. mark as generated + write --------------------------------------------------
sub1(r"(<html[^>]*>)",
     r"\1\n<!-- Arabic (RTL) edition — generated by tools/build_ar.py from index.html + tools/ar_strings.json. Edit those, not this file. -->",
     "generated banner")
out = R / "ar.html"
out.write_text(src, encoding="utf-8")

left = [w for w in ("What I do", "Selected work", "Private projects", "Let's build", "Talk to my agent",
                    "Ask my agent", "Voice CV</", "Toolkit</") if w in src]
print(f"ar.html written: {out.stat().st_size} bytes · keys={len(MAP)} · missed={len(missed)} · english-leftovers={left}")
for m in missed:
    print("  MISS:", m[:100])
sys.exit(1 if missed else 0)
